### PR TITLE
Separated classes and fixed minor errors

### PR DESCRIPTION
**Pull request by jonasraoni**

### CODE REVIEW

**Comment by jonasraoni** [comment]
@asmecher I just fixed minor problems (https://github.com/pkp/COUNTER/pull/4/commits/44a755fd74419d317420f74bcb0525cf2c877648) and separated the classes into individual files (https://github.com/pkp/COUNTER/pull/4/commits/2810682398d046515428b5b72572e95f3d0f0c60) while keeping backwards compatibility with an auto-loader (https://github.com/pkp/COUNTER/commit/d989865b89d742f25e2ca7d6ad03fd7d45e24c13#diff-bb039b5c2e7644e8585ca9079de5d5710bbe4a89afc47a978347aecb408ad9ecR72-R79).

**Comment by asmecher** [comment]
@ctgraham, would you be able to take a look at this? I think we'll need a couple of decisions...
- Whether to create a separate `stable-3_3_0` branch and maintain branches in the future parallel with PKP releases
- Whether to maintain the "official" copy from `ulsdevteam` or `pkp`

@jonasraoni, I'm hesitant to introduce a rewrite with the 3.4.0 release about to come out. I'd lean towards merging a PR to `main` that just includes the bugfix, and treating the rewrite as a separate PR for sometime after 3.4.0 comes out.

**Comment by ctgraham** [comment]
The specific of the bugfixes and the general refacotring of breaking out the classes by file make sense to me.

For long term maintenance, I am comfortable archiving the `ulsdevteam` instance or receiving PRs.

It still strikes me as odd that there isn't a better way to map PHP objects against a schema.  JSON is hyper-flexible but doesn't play well with schema validation; DOMDocument can easily schema-validate after the fact, but not as part of building the object.  Is this really still the best approach ten years later when we have numerous frameworks now integrated in our modernized stack?

**Comment by jonasraoni** [comment]
Yeah, I definetely support delaying bigger changes to post-3.4 👌

FYI, I didn't change almost nothing besides breaking the single file into pieces... I guess it's a very generic code, so another possibility would be to release this as a composer package and make use of its autoloader.

**Comment by ctgraham** [comment]
Regarding whether there is a "better way", Swagger can generate Client SDK model code, for example:
https://app.swaggerhub.com/apis/COUNTER/counter-sushi_5_0_api/5.0.3
(Export -> Client SDK -> php)

**Comment by jonasraoni** [comment]
I didn't know from where this specification came nor inspected the code to understand its purpose, but if it's meant to be used to communicate with an API, using a ready client is the way to go :)

**Comment by asmecher** [comment]
@ctgraham, now that 3.4.0 is out, do I have your go-ahead to merge this into `main`?

**Comment by ctgraham** [comment]
No objections from me.

**Pull request merged**
